#!/bin/bash
set -e

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
	  exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_team_icelab" ]
  then
    echo "Logging into 1Password..."
    # Redirect stderr to stdout because there's where op outputs its prompts :/
    eval "$(op signin team-icelab.1password.com tim@icelab.com.au 2>&1)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get om3v64hfhzh7xhbe5a7weovpnm .ssh/id_rsa
onepassword_get ut2hvppjsveehdiythow7rrwoq .gnupg/tim@openmonkey.com.private.gpg-key

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    echo "Install jq first!" >&2
	  exit 1
  fi
  onepassword_login
  GITHUB_TOKEN=$(op get item qyggzgdwsvhebn77hilwmekxzu | jq -r '.details.sections[2].fields[0].v')
  cat > "$HOME/.secrets" <<EOF
export GITHUB_TOKEN=$GITHUB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add -K

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
  echo "Install gpg first!" >&2
  exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/tim@openmonkey.com.public.gpg-key \
             ~/.gnupg/tim@openmonkey.com.private.gpg-key
