#!/bin/bash
set -e

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
	  exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    # eval "$(op signin --account my.1password.com tim@riley.id.au)"
    # eval "$(op signin --account tim@riley.id.au)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op document get "$1" > "$HOME/$2"
  chmod 0400 "$HOME/$2"
}

onepassword_get j4azb46d3jaz7jpd3rfuy3fc5i .ssh/id_rsa
# onepassword_get ytgvgelomjeazjy3pb4ux4mx4a .gnupg/tim@openmonkey.com.private.gpg-key

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    echo "Install jq first!" >&2
	  exit 1
  fi
  onepassword_login
  GITHUB_TOKEN=$(op get item dzh6z5hbhbh4lbfol3pcjegol4 | jq -r '.details.sections[2].fields[0].v')

  cat > "$HOME/.secrets" <<EOF
export GITHUB_TOKEN=$GITHUB_TOKEN
export GITHUB_REGISTRY_TOKEN=$GITHUB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"

  cat > "$HOME/.secrets.fish" <<EOF
set --export GITHUB_TOKEN "$GITHUB_TOKEN"
set --export GITHUB_REGISTRY_TOKEN "$GITHUB_TOKEN"
EOF
  chmod 600 "$HOME/.secrets.fish"
fi

echo "Storing SSH keys in keychain..."
ssh-add --apple-use-keychain

# echo "Setting up GPG..."
# if ! command -v gpg >/dev/null
# then
#   echo "Install gpg first!" >&2
#   exit 1
# fi

# chmod 700 ~/.gnupg
# gpg --import ~/.gnupg/tim@openmonkey.com.public.gpg-key \
#              ~/.gnupg/tim@openmonkey.com.private.gpg-key
