#!/bin/bash
set -e

if ! command -v heroku >/dev/null
then
  echo "Install Heroku first!" >&2
  exit 1
fi

PLUGINS="$(heroku plugins | awk '{print $1}')"

for PLUGIN in $(cat $(dirname $0)/../_setup/heroku-plugins)
do
  if echo "$PLUGINS" | grep -q "$PLUGIN"
  then
    echo "Plugin '$PLUGIN' is already installed."
  else
    heroku plugins:install "$PLUGIN"
  fi
done
