#!/bin/sh
set -e

cd $(dirname "$0")

# Install dotfiles
brew bundle --file=- <<EOF
  tap "thoughtbot/formulae"
  brew "rcm"
EOF
RCRC=~/.dotfiles/rcrc rcup

# Install applications
brew bundle --global

# ༼ つ ◕_◕ ༽つ Give SETUP
./extract-1password-secrets
./bootstrap-hammerspoon
./install-vscode-extensions
./install-heroku-plugins

# Create additional directories
if [ ! -e ~/Source ]; then
  mkdir ~/Source
fi
if [ ! -e ~/src ]; then
  ln -s ~/Source ~/src
  chflags -h hidden ~/src
fi

if [ ! -e ~/Documents/Files/Screenshots ]; then
  mkdir -p ~/Documents/Files/Screenshots
fi

# Set my default shell to fish
# TODO: need to add /usr/local/bin/fish to /etc/shells
if [ "$SHELL" != "/usr/local/bin/fish" ]
then
  chsh -s /usr/local/bin/fish tim
fi
