#!/bin/sh
set -e

cd $(dirname "$0")

# Install Rosetta (required for iTerm2's Python API; this install should have been
# triggered automatically by iTerm, see https://gitlab.com/gnachman/iterm2/-/issues/10083)
softwareupdate --install-rosetta

# Install dotfiles
brew bundle --file=- <<EOF
  tap "thoughtbot/formulae"
  brew "rcm"
EOF
RCRC=~/.dotfiles/rcrc rcup

# Install applications
brew bundle --global

# ༼ つ ◕_◕ ༽つ Give SETUP
# ./extract-1password-secrets
./bootstrap-hammerspoon
./install-vscode-extensions

# Create additional directories
if [ ! -e ~/Source ]; then
  mkdir ~/Source
fi
if [ ! -e ~/src ]; then
  ln -s ~/Source ~/src
  chflags -h hidden ~/src
fi

if [ ! -e ~/Documents/Files/Screenshots ]; then
  mkdir -p ~/Documents/Files/Screenshots
fi

# Set my default shell to fish
# TODO: need to add /opt/homebrew/bin/fish to /etc/shells
if [ "$SHELL" != "/opt/homebrew/bin/fish" ]
then
  chsh -s /opt/homebrew/bin/fish tim
fi
