#!/bin/sh
# Run by Strap after installing Brewfile dependencies
set -e

cd $(dirname "$0")
./extract-1password-secrets
./bootstrap-hammerspoon
./install-vscode-extensions
./install-heroku-plugins

if [ ! -e ~/Source ]; then
  mkdir ~/Source
fi
if [ ! -e ~/src ]; then
  ln -s ~/Source ~/src
  chflags -h hidden ~/src
fi

if [ ! -e ~/Documents/Files/Screenshots ]; then
  mkdir -p ~/Documents/Files/Screenshots
fi

# TODO: need to add /usr/local/bin/fish to /etc/shells
if [ "$SHELL" != "/usr/local/bin/fish" ]
then
  chsh -s /usr/local/bin/fish tim
fi
