#!/bin/bash

rm -f ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings
ln -s ~/.sublime-text/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

rm -f ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Default\ \(OSX\)\.sublime-keymap
ln -s ~/.sublime-text/Default\ \(OSX\)\.sublime-keymap ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

rm -f ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/ApplySyntax.sublime-settings
ln -s ~/.sublime-text/ApplySyntax.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

rm -f ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Ruby-Quotes.tmPreferences
ln -s ~/.sublime-text/Ruby-Quotes.tmPreferences ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
